name: Mohamad_Alzoubi_personal_website
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  animated_splash_screen: null
  bottom_nav_layout: null
  cupertino_icons: null
  dartz: ^0.10.1
  dio: null
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_launcher_icons: null
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.7
  flutter_svg_provider: null
  font_awesome_flutter: ^10.5.0
  form_field_validator: null
  google_fonts: ^5.1.0
  http: null
  layout: ^1.0.5
  photo_view: ^0.14.0
  responsive_builder: ^0.7.1
  responsive_framework: any
  url_launcher: null
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/projects/
    - assets/images/projects/aerium-v1/
    - assets/images/projects/aerium-v2/
    - assets/images/projects/disneyplus/
    - assets/images/projects/drop/
    - assets/images/projects/flutter_catalog/
    - assets/images/projects/foodybite/
    - assets/images/projects/login_catalog/
    - assets/images/projects/nimbus/
    - assets/images/projects/otp_package/
    - assets/images/projects/outfitr/
    - assets/images/projects/roam/
    - assets/images/projects/chiriane/
    - assets/images/projects/hz_market/
    - assets/images/projects/cashmetaux/


    - assets/fonts/
    - assets/screenshots/